### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by punhanhuseynov** [qurbaniemrah/PragmatechEducation#1]
Readme fayli yaradın və layihəniz haqqında məlumat və template-in linkini yazın

**Comment by qurbaniemrahov** [comment]
men yaratmisam papkanin icindedir

**Comment by punhanhuseynov** [comment]
Hemin fayli daxili folderin icinden cixardib ana folderin icine atin

**Comment by qurbaniemrahov** [comment]
ok
