### ISSUE TITLE
Css

### ISSUE THREAD

**Issue by punhanhuseynov** [qurbaniemrah/PragmatechEducation#2]
https://github.com/qurbaniemrah/PragmatechFoundationProject/blob/954cf76abedd01711bf73061015d8de0d917fa05/My-Project/MyProject/index.html#L9

Css kodları düzgün qosulmayıb

**Comment by qurbaniemrahov** [comment]
beli sonra duzeltdim

**Comment by punhanhuseynov** [comment]
Css kodlari helede duzgun qosulmayib

**Comment by qurbaniemrahov** [comment]
duzeltdim
